# SPDX-License-Identifier: MIT OR Apache-2.0
[package]
name = "ch22-ex01-fetch-concurrently-solution"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }

[lints]
workspace = true
