# SPDX-License-Identifier: MIT OR Apache-2.0
[package]
name = "ch23-error-handling-and-cli-example"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
thiserror = "2.0.20"
